version: '3'
services:
  postgresql:
    container_name: postgresql-${teamname:-defaultASW}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres:latest
    profiles: ["dev", "prod"]
    networks:
      - mynetwork
    ports:
      - "5432:5432"
 
  api:
    container_name: api-${teamname:-defaultASW}
    image: api:latest
    profiles: [ "dev", "prod" ]
    build:
      context: ./api
      args:
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
    networks:
      - mynetwork
    ports:
      - "8080:8080"


volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
