version: '3'
services:
  WIQ_DB:
    container_name: postgresql-${teamname:-defaultASW}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres:latest
    profiles: ["dev", "prod"] 
    networks:
      mynetwork:
        ipv4_address: 10.5.0.10

  api:
    container_name: api-${teamname:-defaultASW}
    image: api:latest
    profiles: ["dev", "prod"]
    build:
      context: ./api
      args:
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
    environment:
      - DATABASE_URL=jdbc:postgresql://WIQ_DB:5432/wiq
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8080:8080
    networks:
      mynetwork:
        ipv4_address: 10.5.0.6
    volumes:
      - ./certs:/etc/letsencrypt
    depends_on:
      - WIQ_DB

  question-generator:
    container_name: question-generator-${teamname:-defaultASW}
    image: question-generator:latest
    profiles: ["dev", "prod"]
    build:
      context: ./questiongenerator
      args:
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    environment:
      - DATABASE_URL=jdbc:postgresql://WIQ_DB:5432/wiq
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      mynetwork:
        ipv4_address: 10.5.0.11
    depends_on:
      - WIQ_DB

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    networks:
      mynetwork:
        ipv4_address: 10.5.0.10

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      mynetwork:
        ipv4_address: 10.5.0.8
    volumes:
      - ./quiz-api/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - ./certs:/etc/letsencrypt/kiwiq.run.place
    depends_on:
      - api

  kiwiq:
    image: kiwiq_en2b
    container_name: kiwiq
    networks:
      mynetwork:
        ipv4_address: 10.5.0.12
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
      - api
      - grafana
      - prometheus
      - certbot
    volumes:
      - ./certs:/etc/certs
    build:
      context: ./nginx_conf

  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      mynetwork:
        ipv4_address: 10.5.0.7
    volumes:
      - grafana_data:/var/lib/grafana
      - ./quiz-api/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./certs:/etc/grafana
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  
volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  mynetwork:
    driver: bridge
    ipam:
      config: 
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1