ifndef::imagesdir[:imagesdir: ../images]
[[section-system-scope-and-context]]
== System Scope and Context
=== Business Context

[plantuml,"C4 Level 1 - Business context diagram",png, align="center", title="Overall view of the business context"]
----
include::../diagrams/c4/C4-Level1.puml[]
----

The WIQ application will communicate with the WikiData API through REST HTTP calls using SPARQL for the queries. It will ask the API for information that will later be used for generating the questions that will be shown to the player. This information will come in the form of text or images.

=== Technical Context

[plantuml,"C4 Level 2 - Container context diagram",png, align="center", title="Overall view of the technical context"]
----
include::../diagrams/c4/C4-Level2.puml[]
----

The WIQ application will be deployed together in the same server. The WIQ client will be deployed on a nginx web server. This client will communicate with the API through HTTPS REST calls and exchange information through JSON objects. The WIQ REST API will be run as a .jar file on the server and connect to a Database run on a postgresql docker container. The connection layer between the SpringBoot API and the database will be JPA.
The REST API will request information to the WikiData REST API through HTTPS calls passing a SPARQL query in order to retrieve data.

