ifndef::imagesdir[:imagesdir: ../images]
[[section-system-scope-and-context]]
== System Scope and Context
=== Business Context

[plantuml,"C4 Level 1 - Business context diagram",png, align="center", title="Overall view of the business context"]
----
include::../diagrams/c4/C4-Level1.puml[]
----
The player interacts with the Kiwiq system, which will communicate with the WikiData API through REST HTTP calls using SPARQL for the queries. It will ask the API for information that will later be used for generating the questions that will be shown to the player. This information will come in the form of text or images.

=== Technical Context

[plantuml,"C4 Level 2 - Container context diagram",png, align="center", title="Overall view of the technical context"]
----
include::../diagrams/c4/C4-Level2.puml[]
----
The Kiwiq system will be deployed together in the same server and contains different modules:

* **Kiwiq Proxy: **
When interacting with the server, an nginx proxy will be tasked with redirecting the queries to the petitions to the Kiwiq client will also be deployed on a nginx web server.

* **Kiwiq Client: **
This client will be served to the client and communicates with the API through HTTPS REST calls and exchanges information through JSON objects.

* **Kiwiq REST API:**
The Kiwiq REST API will be run as a .jar file on the server and connect to a database running on a PostgreSQL docker container. The connection layer between the SpringBoot API and the database will be JPA.

* **Kiwiq database:**
In the database the questions and answers generated by the Question Generator module will be stored, written in Java and using JPA as a connection layer.

* **Question generator:**
The Question Generator will also use the WikiData REST API to retrieve information to generate questions. It  will generate the questions by connecting to the Wikidata REST API through HTTPs calls and passing a SPARQL query to retrieve the data that will later be used in the question generation.


