ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]


== Building Block View


=== Whitebox Overall System

_**Overview Diagram**_
[plantuml,"Business context diagram",png, align="center", title="Overall view of the business context"]
----
include::../diagrams/BusinessContextDiagram.puml[]
----

Motivation::
This will be the general sketch of the elements interacting inside the application, including the external elements that will include the application.

Contained Building Blocks::
****

* **Player:** This is the user that will be playing with our application. They will need to be authenticated to be able to play.
* **WIQ Application:** This is the main application that will reproduce how the game will work. This part will be more detailed in the following parts.
* **WikiData API:** This is an external API, which will provide us with the information to produce the questions.

****

Important Interfaces::
This part will be more detailed later, since the structure of the different interfaces/classes has not been discussed by the team yet.


=== Level 2

Motivation::
An inner view on the WIQ Application and its components inside. How the WIQ application will be structured inside and its main components.

Contained Building Blocks::
****
* **WIQ Client:** This is the connection between the user and the application. It will allow the users to play the WIQ game. This part will be developed in React with Typescript for its clear component structure, simplified code quality and separation of concerns.
* **WIQ REST API:** This is the part responsible for managing the users that log into the application, managing also the logic of the game and sending the request to the Wikidata API for the question generation. This part is going to be developed in SpringBoot due to its foundations on the Java programming language, which is the language that the developers find the easiest to develop in.
* **Question Generator Module:** This component is in charge of everything related with the questions. It retrieves the information from WikiData QS and stores it in the WIQ Database, which later is queried for questions and answers from the REST API.
* **WIQ Database:** This is where the most important data is going to be stored. Such as, users questions and other game info that will be specified in the future. The database we chose to use is PostgreSQL, since it is compatible with Docker and it's an object-relational kind of database, which is easier for the developers to use. Another alternative would've been to use MySQL.
****

Important Interfaces::
We are connecting the front end with the back end via REST API. Also, the Question Generator Module communicates with WikiData QS this way.
The Question Generator Module connects to the WIQ DataBase through JPA.
In the near future, we are planning on allowing HTTPS connections, so there would be a proxy server in between the user's agent and the back end.


