ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]

== Deployment View
[plantuml,"Deployment diagram",png]
----
include::../diagrams/deployment/DeploymentDiagram.puml[]
----

=== Infrastructure Level 1

Motivation::

The above diagram shows the initial version of the architecture and the division between its components. We will be using a simple client-server architecture, and the server will be querying Wikidata for the questions. By separating the architecture in this way we enforce a clear separation between the client/frontend and the server/backend, which benefits the system as a whole because so long the common API is implemented, the implementations themselves shall remain interchangeable.

Quality and/or Performance Features::

As stated before, we consider the main advantage of this architecture the interchangeability of the components. There remain details to be scratched out though, but this is still an initial version.

Mapping of Building Blocks to Infrastructure::

 * The webapp/frontend/client is contained within the `webapp` subfolder.
 * The API/backend is contained within the `api` subfolder.
 ** The database will be generated on deployment.
 ** Wikidata is an external component, so although it is an important part of the deployment architecture, it is something we do not have access to changing.
 * The question generator is a separate component that will be deployed on the server only at the beginning of the system. It is contained within the `questiongenerator` subfolder.

=== Infrastructure Level 2

==== Frontend/Client

This component is self-contained and does not require much explanation.

==== API/Backend

===== Server

Our main idea is that the server will be a self-contained .jar file with all the dependencies required within. It will communicate with the database and periodically query Wikidata to generate questions until a certain number has been obtained once per minute to fill up the database and improve speed.

===== Database

The database will contain the data used by the system. Therefore, it will contain user data, as well as the data related to the questions and their answers. The databases to store the questions (and therefore the answers) and the user data might be different, though.

===== Question Generator
The question generator will be run only at the beginning of the application. It will connect with Wikidata using SPARQL to generate questions and answers and store them in the database. This question generation will generate all the questions used by the application at once.
