ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts

.Domain Model
This is the first version of the diagram, it will be updated if needed.

[plantuml,"ConceptsDomainModel1",png]
----
@startuml

enum Category {
    HISTORY
    GEOGRAPHY
    SCIENCE
}

enum Type {
    TEXT
    IMAGE
    AUDIO
}

class Question{
    id: long
    content: String
    answers: List<Answer>
    correct: Answer
    category: Category
    language: String
    Type: Type
}

class User{
    answeredQuestions: int
}

class UserStat{
}

class Answer {
    text: String
    category: Category
    Type: Type
}

class Game {
    user: User
    questions: List<Question>
}


class Ranking {
    
}

User  o--> Question
User -->  UserStat
Game  o--> Question
Game --> User
Question --> Answer
Ranking  --> User

@enduml
----

|===
| Class | Explanation
| Question | The model of the questions, has a type to specify if it is text, image or audio. Stores both right and wrong answers
| User | The people using the application, they have statistics and take part in a ranking to compete
| Answer | Models each possible answer, created to reuse answers that are common to different questions, as well as distractors
| Game | It is created when the user starts a game and destroyed just when it ends.
|===

.Architecture and design patterns
We decided to use a React based frontend with BootSpring for the backend, which will follow the model view controller pattern to make the code clear.

.User Experience
As this is a game, the focus must be in user experience so players can have an enjoyable experience, for achieving this, the response time should be as low as possible and the interfaces should be intuitive and beautiful.

.Safety and Security concepts:
Authentication is done in SpringBoot3. Passwords must be hashed both in client and in API to ensure as much security as possible.

.Robustness:
It is desired to make the application as independant as possible from Wikidata. This way, if it is down our application can still manage to be available for our users.
In order to archieve this, we will implement two modules regarding questions, one for retrieving it from Wikidata and storing it in our own DB and another for getting questions from it.

.Development concepts:
Our code will be deployed within an Azure's Virtual Machine using continuous integration. 

.Under-the-hood:
Regarding Data persistence, our project has two DB, one for storing questions as stated before while the other one will be in charge of storing any other meaningful data for the game such us users or game's histories.
