ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts


[role="arc42help"]
****


.Domain Model
These diagram is just a sketch, it should be replaced by a more accurate version upon discussion.

[plantuml,"ConceptsDomainModel1",png]
----
@startuml

enum Category {
    HISTORY
    GEOGRAPHY
    MATHS
}

class Question{
    id: int
    content: String
    category: Category
    language: String
}

class User{
    id: int
    name: String
    email: String
    password: String
    answered: List<Question>
}

class Score{
    user: User
    rightRate: float
    timeAvg: float
    answeredQuestions: int
}

User o--> Question
User --> Score

@enduml
----

|===
| Class | Explanation
| Question | The model of the questions
| User | The people using the application
| Score | A class that keeps tracks of each user scores
|===

.Architecture and design patterns
We decided to use a React based frontend with BootSpring for the backend, which will follow the model view controller pattern to make the code clear.

.User Experience
As this is a game, the focus must be in user experience so players can have an enjoyable experience, for achieving this, the response time should be as low as possible and the interfaces should be intuitive and beautiful.
