ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts

.Domain Model
This is the first version of the diagram, it will be updated if needed.

[plantuml,"ConceptsDomainModel1",png]
----
@startuml
enum QuestionCategory {
    GEOGRAPHY
    SPORTS
    MUSIC
}

enum AnswerCategory {
    CAPITAL_CITY
    COUNTRY
    SONG
    STADIUM
    BALLON_DOR
}

enum QuestionType{
    TEXT
    IMAGE
    AUDIO
}

class Question{
    content: String
    answers: List<Answer>
    correctAnswer: Answer
    questionCategory: QuestionCategory
    type: QuestionType
    games: List<Game>
}

class User{
    username: String
    email: String
    password: String
    role: String
    games: List<Game>
}

class Statistics{
    correct: Long
    wrong: Long
    total: Long
    user: User
}

class Answer {
    text: String
    category: AnswerCategory
    language: String
}

class Game {
    user: User
    questions: List<Question>
    rounds: int
    actualRound: int
    correctlyAnsweredQuestions: int
    language: String
    roundStartTime: LocalDateTime
    roundDuration: Integer
    currentQuestionAnswered: boolean
    isGameOver: boolean
}


User "1"--"1" Statistics
Game "n"--"n" Question
Game "1" -- "n" User
Question "n" -- "n" Answer

@enduml
----

|===
| Class | Explanation
| Question | The model of the questions, has a type to specify if it is text, image or audio. Stores both right and wrong answers
| User | The people using the application, they have statistics and take part in a ranking to compete
| Answer | Models each possible answer, created to reuse answers that are common to different questions, as well as distractors
| Game | It is created when the user starts a game and includes the rounds that the user has to answer
|===

.Question Generator
The Question Generator is an important part of our application, it is already briefly described in Section 6, but mopre insight is given here.

The Question Generator module is written in Java and connects via HTTP with Wikidata query service. 
It follows a template design pattern where each Java class is responsible for generating the questions and answers.
The query is ran against Wikidata and it returns a text in JSON format that is processed into the question and answers, which are later stored in the DB.

.Architecture and design patterns
We decided to use a React based frontend with BootSpring for the backend, which will follow the model view controller pattern to make the code clear.

.User Experience
As this is a game, the focus must be in user experience so players can have an enjoyable experience, for achieving this, the response time should be as low as possible and the interfaces should be intuitive and beautiful.

.Safety and Security concepts:
Authentication is done in SpringBoot3. Passwords must be hashed both in client and in API to ensure as much security as possible.

.Robustness:
It is desired to make the application as independant as possible from Wikidata. This way, if it is down our application can still manage to be available for our users.
In order to archieve this, we will implement two modules regarding questions, one for retrieving it from Wikidata and storing it in our own DB and another for getting questions from it.

.Development concepts:
Our code will be deployed within an Azure's Virtual Machine using continuous integration. 

.Under-the-hood:
Regarding Data persistence, our project has two DB, one for storing questions as stated before while the other one will be in charge of storing any other meaningful data for the game such us users or game's histories.
