@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!include <c4/C4_Context.puml>

title Context Diagram for the WIQ System
AddElementTag("Person", $bgColor="#salmon", $fontColor="#white")
AddElementTag("Internal system", $bgColor="#darksalmon", $fontColor="#white")
AddElementTag("External system", $bgColor="#peachpuff", $fontColor="#963b17")

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())


'Containers
Person(player, Player,"An authenticated player that wants to play WIQ games", $tags="Person")

Container(wiq, "WIQ Application","", "Application that allows the users to play WIQ games", $tags="Internal system")

System_Ext(wikidata,"WikiData API","Contains the information used for the question generation", $tags="External system")

'RELATIONS
Rel(player,wiq,"Plays games")
Rel(wiq,wikidata,"Asks for data for question generation")
SHOW_LEGEND()
@enduml