  version: '3'
  services:
    WIQ_DB:
      container_name: postgresql-${teamname:-defaultASW}
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      image: postgres:latest
      networks:
        mynetwork:

    api:
      container_name: api-${teamname:-defaultASW}
      build:
        context: ../../api
        args:
          DATABASE_USER: ${DATABASE_USER}
          DATABASE_PASSWORD: ${DATABASE_PASSWORD}
          JWT_SECRET: ${JWT_SECRET}
          SSL_PASSWORD: ${SSL_PASSWORD}
        dockerfile: Dockerfile
      environment:
        - DATABASE_URL=jdbc:postgresql://WIQ_DB:5432/wiq
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - JWT_SECRET=${JWT_SECRET}
        - SSL_PASSWORD=${SSL_PASSWORD}
      ports:
        - 8443:8443
      networks:
        mynetwork:
      volumes:
        - /certs:/etc/letsencrypt/live/kiwiq.run.place:ro
      depends_on:
        - WIQ_DB

    question-generator:
      container_name: question-generator-${teamname:-defaultASW}
      build:
        context: ../../questiongenerator
        args:
          DATABASE_USER: ${DATABASE_USER}
          DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        dockerfile: Dockerfile
      environment:
        - DATABASE_URL=jdbc:postgresql://WIQ_DB:5432/wiq
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      networks:
        mynetwork:
      depends_on:
        - WIQ_DB

  volumes:
    postgres_data:
    certs:

  networks:
    mynetwork:
      driver: bridge
