@startuml login
title Login Sequence Diagram
actor Client #darkolivegreen
participant API #darkolivegreen
database DB #darkolivegreen
skinparam Style strictuml
skinparam SequenceMessageAlignment center

Client -> API : enters credentials
activate API #darkolivegreen
API -> DB    : check credentials correct
alt #darkseagreen credentials correct
    activate DB #darkolivegreen
    DB --> API     : returns result
    deactivate DB
    API -> API : generate jwt and refresh tokens
    API -> DB    : save tokens
    activate DB #darkolivegreen
    DB --> API     : saves tokens
    deactivate DB
    API --> Client : return jwt dto
    deactivate API
else credentials incorrect
    activate DB #darkolivegreen
    DB --> API     : returns error
    deactivate DB
    activate API #darkolivegreen
    API --> Client : return 403 error
    deactivate API
end


@enduml