@startuml Game's life cycle
title Game Sequence Diagram
actor Client #darkolivegreen
participant API #darkolivegreen
database DB #darkolivegreen

skinparam Style strictuml
skinparam SequenceMessageAlignment center

Client -> API : start game
activate API #darkolivegreen
API -> DB : store game info
activate DB #darkolivegreen
DB --> API : game info stored
deactivate DB
API --> Client : return game info
deactivate API
loop #darkseagreen Round
  Client -> API : start round
  activate API #darkolivegreen
  API -> DB : ask for question
  activate DB  #darkolivegreen
  DB --> API : return question
  deactivate DB
  API --> Client : return question with all answers
  deactivate API
  Client -> API  : send chosen answer
  activate API #darkolivegreen
  API -> API    : check answer is correct
  API -> DB     : update game info
  activate DB #darkolivegreen
  DB --> API    : game info updated
 deactivate DB
  API --> Client : inform user if guessed right


end loop One question

API -> DB : [if last round] update ranking
activate DB #darkolivegreen
DB --> API : ranking updated
deactivate DB
API --> Client : inform user if guessed right
deactivate API

@enduml