@startuml login

actor Client

skinparam Style strictuml
skinparam SequenceMessageAlignment center

Client --> API : enters credentials
API --> BD     : check credentials correct
BD --> API     : return user token
API --> BD     : save SWT
API --> Client : return user token


@enduml