@startuml sign up
title Sign Up Sequence Diagram
actor Client #darkolivegreen
participant API #darkolivegreen
database DB #darkolivegreen
skinparam Style strictuml
skinparam SequenceMessageAlignment center

Client -> API : account details
activate API #darkolivegreen
API -> API : validate details
API -> DB  : check email is unused
alt #darkseagreen email is unused
    activate DB #darkolivegreen
    DB --> API  : email is unused
    deactivate DB

    API -> DB  : register user
    activate DB #darkolivegreen
    DB --> API  : user registered
    deactivate DB
    API --> Client  : return confirmation
    deactivate API
else email is used
    activate DB #darkolivegreen
    DB --> API  : email is used
    deactivate DB
    activate API #darkolivegreen
    API --> Client  : 400 error
    deactivate API
end
@enduml