@startuml question generator
title Question Generator Sequence Diagram
participant QuestionGenerator #darkolivegreen
participant WikiDataQS #darkolivegreen
database DB #darkolivegreen
skinparam Style strictuml
skinparam SequenceMessageAlignment center

loop #darkseagreen Generate question templates
activate QuestionGenerator #darkolivegreen
QuestionGenerator -> WikiDataQS  : request query template
activate WikiDataQS #darkolivegreen
QuestionGenerator <-- WikiDataQS  : returns query answers
deactivate WikiDataQS
QuestionGenerator -> QuestionGenerator  : process query answer
QuestionGenerator -> DB  : store answers
activate DB #darkolivegreen
QuestionGenerator -> DB  : store questions
DB --> QuestionGenerator  :  info saved
deactivate DB
end loop

deactivate QuestionGenerator
@enduml