scrape_configs:
  - job_name: 'WiqMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ['kiwiq.run.place:8443']
        labels:
          application: 'WIQ API'