scrape_configs:
  - job_name: 'WiqMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ['<%= ENV["API_URI"] %>']
        labels:
          application: 'WIQ API'