name: Deploy on release

on:
  release:
    types: [published]
  push:
    branches:
      - fix/actions
jobs:
  docker-push-api:
    runs-on: ubuntu-latest
    #needs: [ e2e-tests ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          name: arquisoft/wiq_en2b/api
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: api
          buildargs: API_URI
  docker-push-webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    #needs: [ e2e-tests ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          API_URI: http://${{ secrets.DEPLOY_HOST }}:8080
          teamname: wiq_en2b
        with:
          name: arquisoft/wiq_en2b/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_URI
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-api, docker-push-webapp]
    steps:
    - uses: actions/checkout@v4
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      env:
        API_URI: ${{ secrets.DEPLOY_HOST }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          wget https://raw.githubusercontent.com/arquisoft/wiq_en2b/master/docker-compose.yml -O docker-compose.yml
          wget https://raw.githubusercontent.com/arquisoft/wiq_en2b/master/.env -O .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "API_URI=http://${{ secrets.DEPLOY_HOST }}:8080" >> .env
          docker compose --profile prod down
          docker compose --profile prod up -d
